spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vrshow?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 12345
  servlet:
    multipart:
    max-file-size: 30MB
    max-request-size: 30MB

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

  type-aliases-package: com.vera.trade.model


#配置外部访问文件
vera:
  filePath : file:/E:/profile/


server:
  port: 8090


logging:
  file: logging/mylog.log
